### ISSUE TITLE
Unable to build with android@6.4.0

### ISSUE THREAD

**Issue by cedw032** [skwasjer/skwas-cordova-plugin-datetimepicker#37]
**Describe the bug**
When I try to build my project using Cordova I receive and error and the following stack trace
```
BUILD FAILED in 2s
27 actionable tasks: 3 executed, 24 up-to-date
/Users/chadedwards/git/fergus_mobile/platforms/android/gradlew: Command failed with exit code 1 Error output:
/Users/chadedwards/git/fergus_mobile/platforms/android/src/com/skwas/cordova/datetimepicker/DateTimePicker.java:306: error: local variable callbackContext is accessed from within inner class; needs to be declared final
					callbackContext.success(new JSONObject());
```

**To Reproduce**
```
cordova plugin add skwas-cordova-plugin-datetimepicker
cordova build android
```

**Expected behavior**
Build success

**Screenshots**
Not applicable

**Cordova**
List Cordova versions by running:
- `cordova -v` - `8.1.2 (cordova-lib@8.1.1)`
- `cordova platform ls` - `android 6.4.0`

**Development OS (please complete the following information):**
 - Mac Mojave

**Device (please complete the following information):**
Build error not runtime error

**Additional context**

**Comment by skwasjer** [comment]
Thanks for reporting, it should be fixed now.
