### ISSUE TITLE
Error while taking build

### ISSUE THREAD

**Issue by go2hyder** [skwasjer/skwas-cordova-plugin-datetimepicker#25]
I am getting the following error while taking the build

`...pathto\platforms\android\src\com\skwas\cordova\datetimepicker\DateTimePicker.java:107: error: strings in switch are not supported in -source 1.6
           switch (action) {
                       ^
  (use -source 7 or higher to enable strings in switch)
Note: Some input files use or override a deprecated API`

cordova version :- 7.1.0
cordova android :- 6.1.0

**Comment by skwasjer** [comment]
This is on the `develop` branch, just needs a little bit of refactoring (if/else instead of switch) to keep it backwards compatible to older versions. A PR would be nice because I am not able to do and test this at the moment.

Offending commit: https://github.com/skwasjer/skwas-cordova-plugin-datetimepicker/commit/04c74ae69515a406742fe81806320e63dfe84ba0#diff-49f235c043431f50944d14b005d9889bR108

**Comment by skwasjer** [comment]
Should be fixed, please try. Please note that there is still a known issue in the `develop` with regards to minDate/maxDate options, hence why I didn't release it to npm yet.
